In [1]:
import numpy as np

In [8]:
mu = np.array([0.05, 0.06, 0.08, 0.06])
vol = np.array([0.15, 0.2, 0.25, 0.3])
C = np.matrix([[1, 0.1, 0.4, 0.5], [0.1, 1, 0.7, 0.4], [0.4, 0.7, 1, 0.8], [0.5, 0.4, 0.8, 1]])
mu, vol, C

(array([0.05, 0.06, 0.08, 0.06]),
 array([0.15, 0.2 , 0.25, 0.3 ]),
 matrix([[1. , 0.1, 0.4, 0.5],
         [0.1, 1. , 0.7, 0.4],
         [0.4, 0.7, 1. , 0.8],
         [0.5, 0.4, 0.8, 1. ]]))

In [ ]:
min f(x)
s.a. g(x)

L(x, l) = f(x)-l*g(x)

min xT*Sigma*x - gamma*mu*

dL/dx = 2*x*Sigma - (gmma mu)=0
